# Generated by Django 5.0.6 on 2024-07-05 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='embalagem',
            old_name='name',
            new_name='nome',
        ),
    ]
